//! Build script for finetype DuckDB extension.
//!
//! When the `embed-models` feature is enabled, embeds the active model
//! (flat CharCNN or tiered) at compile time. Detects tiered models by
//! the presence of tier_graph.json in the default model directory.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Convert a path to a string safe for use inside `include_bytes!()` / `include_str!()`.
/// On Windows, `canonicalize()` produces `\\?\D:\...` paths with backslashes that Rust
/// interprets as escape sequences. Forward slashes work on all platforms.
fn portable_path(p: &Path) -> String {
    p.canonicalize()
        .unwrap()
        .to_string_lossy()
        .replace('\\', "/")
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let models_base = PathBuf::from(&manifest_dir).join("models");

    // Rerun if models change
    println!("cargo:rerun-if-changed={}", models_base.display());

    #[cfg(feature = "embed-models")]
    generate_embedded_models(&models_base);

    #[cfg(not(feature = "embed-models"))]
    let _ = models_base;
}

#[cfg(feature = "embed-models")]
fn generate_embedded_models(models_base: &Path) {
    // Follow the models/default symlink to find the active model
    let default_link = models_base.join("default");
    let model_dir = if default_link.exists() {
        std::fs::read_link(&default_link)
            .map(|target| {
                if target.is_relative() {
                    models_base.join(target)
                } else {
                    target
                }
            })
            .unwrap_or_else(|_| models_base.join("char-cnn-v4"))
    } else {
        models_base.join("char-cnn-v4")
    };

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = PathBuf::from(&out_dir).join("embedded_models.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n\n");

    // Detect model type: tiered (has tier_graph.json) or flat (has model.safetensors)
    let is_tiered = model_dir.join("tier_graph.json").exists();

    if is_tiered {
        generate_tiered_embeds(&model_dir, &mut code);
        code.push_str("\npub const EMBEDDED_MODEL_TYPE: &str = \"tiered\";\n");
    } else {
        generate_flat_embeds(&model_dir, &mut code);
        code.push_str("\npub const EMBEDDED_MODEL_TYPE: &str = \"flat\";\n");
    }

    fs::write(&dest, code)
        .unwrap_or_else(|e| panic!("Failed to write {}: {}", dest.display(), e));
}

/// Generate embeds for a flat CharCNN model (single model.safetensors + labels.json + config.yaml).
#[cfg(feature = "embed-models")]
fn generate_flat_embeds(model_dir: &Path, code: &mut String) {
    assert!(
        model_dir.join("model.safetensors").exists(),
        "Flat model not found at {:?}. Place model files in models/ or create a models/default symlink.",
        model_dir
    );

    let weights_path = portable_path(&model_dir.join("model.safetensors"));
    let labels_path = portable_path(&model_dir.join("labels.json"));
    let config_path = portable_path(&model_dir.join("config.yaml"));

    code.push_str(&format!(
        "pub const FLAT_WEIGHTS: &[u8] = include_bytes!(\"{weights_path}\");\n"
    ));
    code.push_str(&format!(
        "pub const FLAT_LABELS: &[u8] = include_bytes!(\"{labels_path}\");\n"
    ));
    code.push_str(&format!(
        "pub const FLAT_CONFIG: &[u8] = include_bytes!(\"{config_path}\");\n"
    ));
}

/// Generate embeds for a tiered model (tier_graph.json + multiple tier subdirectories).
///
/// Produces:
/// - `TIER_GRAPH: &[u8]` — the tier_graph.json bytes
/// - `get_tiered_model_data(dir: &str) -> Option<(&[u8], &[u8], &[u8])>` — lookup function
#[cfg(feature = "embed-models")]
fn generate_tiered_embeds(model_dir: &Path, code: &mut String) {
    let graph_path = model_dir.join("tier_graph.json");
    assert!(
        graph_path.exists(),
        "Tiered model tier_graph.json not found at {:?}.",
        model_dir
    );

    // Embed tier_graph.json
    let graph_portable = portable_path(&graph_path);
    code.push_str(&format!(
        "pub const TIER_GRAPH: &[u8] = include_bytes!(\"{graph_portable}\");\n\n"
    ));

    // Find all tier subdirectories that contain model.safetensors
    let mut tier_dirs: Vec<(String, PathBuf)> = Vec::new();
    for entry in fs::read_dir(model_dir).expect("Failed to read model directory") {
        let entry = entry.expect("Failed to read directory entry");
        let path = entry.path();
        if path.is_dir() && path.join("model.safetensors").exists() {
            let dir_name = entry.file_name().to_string_lossy().to_string();
            tier_dirs.push((dir_name, path));
        }
    }
    tier_dirs.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate the lookup function
    code.push_str(
        "pub fn get_tiered_model_data(dir_name: &str) -> Option<(&'static [u8], &'static [u8], &'static [u8])> {\n",
    );
    code.push_str("    match dir_name {\n");

    for (dir_name, dir_path) in &tier_dirs {
        let weights = portable_path(&dir_path.join("model.safetensors"));
        let labels = portable_path(&dir_path.join("labels.json"));
        let config = portable_path(&dir_path.join("config.yaml"));

        code.push_str(&format!(
            "        \"{dir_name}\" => Some((\n\
             \x20           include_bytes!(\"{weights}\"),\n\
             \x20           include_bytes!(\"{labels}\"),\n\
             \x20           include_bytes!(\"{config}\"),\n\
             \x20       )),\n"
        ));
    }

    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n");
}
