//! Build script for finetype DuckDB extension.
//!
//! When the `embed-models` feature is enabled, this script embeds the flat CharCNN
//! model weights, labels, and config at compile time via `include_bytes!`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// Convert a path to a string safe for use inside `include_bytes!()` / `include_str!()`.
/// On Windows, `canonicalize()` produces `\\?\D:\...` paths with backslashes that Rust
/// interprets as escape sequences. Forward slashes work on all platforms.
fn portable_path(p: &Path) -> String {
    p.canonicalize()
        .unwrap()
        .to_string_lossy()
        .replace('\\', "/")
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let models_base = PathBuf::from(&manifest_dir).join("models");

    // Rerun if models change
    println!("cargo:rerun-if-changed={}", models_base.display());

    #[cfg(feature = "embed-models")]
    generate_embedded_models(&models_base);

    #[cfg(not(feature = "embed-models"))]
    let _ = models_base;
}

#[cfg(feature = "embed-models")]
fn generate_embedded_models(models_base: &Path) {
    // Find model directory — follow default symlink or scan for char-cnn-*
    let default_link = models_base.join("default");
    let flat_dir = if default_link.exists() {
        std::fs::read_link(&default_link)
            .map(|target| {
                if target.is_relative() {
                    models_base.join(target)
                } else {
                    target
                }
            })
            .unwrap_or_else(|_| find_model_dir(models_base))
    } else {
        find_model_dir(models_base)
    };

    // Verify flat model exists
    assert!(
        flat_dir.join("model.safetensors").exists(),
        "Model not found at {:?}. Place model files in models/char-cnn-*/ or create a models/default symlink.",
        flat_dir
    );

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = PathBuf::from(&out_dir).join("embedded_models.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n");
    code.push_str("// Embeds model weights, labels, and configs at compile time.\n\n");

    let weights_path = portable_path(&flat_dir.join("model.safetensors"));
    let labels_path = portable_path(&flat_dir.join("labels.json"));
    let config_path = portable_path(&flat_dir.join("config.yaml"));

    code.push_str(&format!(
        "pub const FLAT_WEIGHTS: &[u8] = include_bytes!(\"{weights_path}\");\n"
    ));
    code.push_str(&format!(
        "pub const FLAT_LABELS: &[u8] = include_bytes!(\"{labels_path}\");\n"
    ));
    code.push_str(&format!(
        "pub const FLAT_CONFIG: &[u8] = include_bytes!(\"{config_path}\");\n"
    ));

    fs::write(&dest, code).unwrap_or_else(|e| panic!("Failed to write {}: {}", dest.display(), e));
}

/// Find the most recent char-cnn-* model directory by name (lexicographic).
#[cfg(feature = "embed-models")]
fn find_model_dir(models_base: &Path) -> PathBuf {
    let mut dirs: Vec<_> = fs::read_dir(models_base)
        .expect("Failed to read models directory")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            p.is_dir()
                && p.file_name()
                    .and_then(|n| n.to_str())
                    .map(|n| n.starts_with("char-cnn-"))
                    .unwrap_or(false)
        })
        .collect();
    dirs.sort();
    dirs.last()
        .cloned()
        .unwrap_or_else(|| models_base.join("char-cnn-v4"))
}
